export type ColorMode = 'stone' | 'neutral' | 'zinc' | 'gray' | 'blue' | 'green' | 'red' | 'yellow' | 'indigo' | 'purple' | 'pink' | 'amber' | 'cyan' | 'teal' | 'lime' | 'orange'
  | 'slate' | 'rose' | 'violet' | 'sky' | 'fuchsia' | 'emerald';

export const ColorModeTextClassName: Record<ColorMode, string> = {
  stone: 'text-stone-800',
  neutral: 'text-neutral-800',
  zinc: 'text-zinc-800',
  gray: 'text-gray-800',
  blue: 'text-blue-800',
  green: 'text-green-800',
  red: 'text-red-800',
  yellow: 'text-yellow-800',
  indigo: 'text-indigo-800',
  purple: 'text-purple-800',
  pink: 'text-pink-800',
  amber: 'text-amber-800',
  cyan: 'text-cyan-800',
  teal: 'text-teal-800',
  lime: 'text-lime-800',
  orange: 'text-orange-800',
  slate: 'text-slate-800',
  rose: 'text-rose-800',
  violet: 'text-violet-800',
  sky: 'text-sky-800',
  fuchsia: 'text-fuchsia-800',
  emerald: 'text-emerald-800',
};

export const ColorModeNeutralBackgroundClassName: Record<ColorMode, string> = {
  stone: 'bg-stone-200',
  neutral: 'bg-neutral-200',
  zinc: 'bg-zinc-200',
  gray: 'bg-gray-200',
  blue: 'bg-blue-200',
  green: 'bg-green-200',
  red: 'bg-red-200',
  yellow: 'bg-yellow-200',
  indigo: 'bg-indigo-200',
  purple: 'bg-purple-200',
  pink: 'bg-pink-200',
  amber: 'bg-amber-200',
  cyan: 'bg-cyan-200',
  teal: 'bg-teal-200',
  lime: 'bg-lime-200',
  orange: 'bg-orange-200',
  slate: 'bg-slate-200',
  rose: 'bg-rose-200',
  violet: 'bg-violet-200',
  sky: 'bg-sky-200',
  fuchsia: 'bg-fuchsia-200',
  emerald: 'bg-emerald-200',
};

export const ColorModeLightBackgroundClassName: Record<ColorMode, string> = {
  stone: 'bg-stone-100',
  neutral: 'bg-neutral-100',
  zinc: 'bg-zinc-100',
  gray: 'bg-gray-100',
  blue: 'bg-blue-100',
  green: 'bg-green-100',
  red: 'bg-red-100',
  yellow: 'bg-yellow-100',
  indigo: 'bg-indigo-100',
  purple: 'bg-purple-100',
  pink: 'bg-pink-100',
  amber: 'bg-amber-100',
  cyan: 'bg-cyan-100',
  teal: 'bg-teal-100',
  lime: 'bg-lime-100',
  orange: 'bg-orange-100',
  slate: 'bg-slate-100',
  rose: 'bg-rose-100',
  violet: 'bg-violet-100',
  sky: 'bg-sky-100',
  fuchsia: 'bg-fuchsia-100',
  emerald: 'bg-emerald-100',
};


export const ColorModeDarkBackgroundClassName: Record<ColorMode, string> = {
  stone: 'bg-stone-300',
  neutral: 'bg-neutral-300',
  zinc: 'bg-zinc-300',
  gray: 'bg-gray-500',
  blue: 'bg-blue-500',
  green: 'bg-green-500',
  red: 'bg-red-500',
  yellow: 'bg-yellow-500',
  indigo: 'bg-indigo-500',
  purple: 'bg-purple-500',
  pink: 'bg-pink-500',
  amber: 'bg-amber-500',
  cyan: 'bg-cyan-500',
  teal: 'bg-teal-500',
  lime: 'bg-lime-500',
  orange: 'bg-orange-500',
  slate: 'bg-slate-500',
  rose: 'bg-rose-500',
  violet: 'bg-violet-500',
  sky: 'bg-sky-500',
  fuchsia: 'bg-fuchsia-500',
  emerald: 'bg-emerald-500',
};

export const ColorModeBorderClassName: Record<ColorMode, string> = {
  stone: 'border-stone-500',
  neutral: 'border-neutral-500',
  zinc: 'border-zinc-500',
  gray: 'border-gray-500',
  blue: 'border-blue-500',
  green: 'border-green-500',
  red: 'border-red-500',
  yellow: 'border-yellow-500',
  indigo: 'border-indigo-500',
  purple: 'border-purple-500',
  pink: 'border-pink-500',
  amber: 'border-amber-500',
  cyan: 'border-cyan-500',
  teal: 'border-teal-500',
  lime: 'border-lime-500',
  orange: 'border-orange-500',
  slate: 'border-slate-500',
  rose: 'border-rose-500',
  violet: 'border-violet-500',
  sky: 'border-sky-500',
  fuchsia: 'border-fuchsia-500',
  emerald: 'border-emerald-500',
};
